version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: jinwoo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jinwoo_db
      MYSQL_USER: jinwoo
      MYSQL_PASSWORD: jinwoopassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - jinwoo-network

networks:
  jinwoo-network:
    driver: bridge
